### PR TITLE
Added include/exclude to json outputstream just like channel

### PR DESCRIPTION
**Pull request by jhorwit2**

### CODE REVIEW

**Comment by stevedonnelly** [comment]
have you tested this when both include and exclude are null?  based on a quick read of FIlteredBundle it looks like it might NPE: https://github.com/addthis/hydra/blob/master/hydra-task/src/main/java/com/addthis/hydra/task/output/FilteredFormat.java#L55

**Comment by jhorwit2** [comment]
I copy pasted this logic directly from https://github.com/addthis/hydra/blob/ffd708a1078f2bcb24cc873d4f12ef18f9d410b4/hydra-task/src/main/java/com/addthis/hydra/task/output/OutputStreamChannel.java

I'm very surprised no one has hit that condition yet. I can add an if not null on exclude?

**Comment by jhorwit2** [comment]
Actually this won't NPE because the class will only make the filter if ` if (include != null || exclude != null) {`

**Comment by tea-dragon** [comment]
Is there some reason filtered data output did not suffice?

**Pull request merged**
