### PR TITLE
Add prometheus metrics for spawn, minion, mqmaster, and mqworker

### PR DESCRIPTION
**Pull request by kxingit**
Addressed comments in https://github.com/addthis/hydra/pull/270

### CODE REVIEW

**Comment by tedpearson** [comment]
If we do the things that MetricsServletMaker was doing for metricsServlet, are all the handler.start/stop things still required?

**Comment by kxingit** [comment]
I think the original MetricsServletMaker that is supposed to handle "metrics" never worked properly. So if I run master branch and then curl: 
$ curl localhost:5555/ping
ACK
$ curl localhost:5555/metrics/
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 503 Service Unavailable</title>

**Comment by tedpearson** [comment]
Confirmed in production. Funky.

One more minor thing. Can we rename `handler` since it's not obvious from the name what it does.

**Comment by tedpearson** [comment]
Does this still need a review @kxingit ?

**Comment by kxingit** [comment]
@tedpearson nope, another branch has been merged https://github.com/addthis/hydra/pull/270
this branch can be deleted

**Pull request closed without merging**
