### PR TITLE
Added empty output aliased to FilteredDataOutput. Ref T53231

### PR DESCRIPTION
**Pull request by yuesong**
Instead of adding a new class, I opted for an alias to FilterDataOutput with empty chain filter and an empty tree output.

I wanted to use unary (true) in extra-filters, but that will require jobs to include extra-filters. An empty chain was the best thing I could come up with.

### CODE REVIEW

**Comment by tedpearson** [comment]
Any reason not to consider moving unary into reference.conf to support this feature?

**Comment by tea-dragon** [comment]
What is the purpose of the filtered data output wrapper?

I think I would also prefer if such an output did not entail writing files or constructing a tree mapper (for testing purposes).

**Comment by yuesong** [comment]
Uh.. you are right. I was looking for examples and saw FilteredDataOutput. That somehow stuck with me. Could've been an alias to an empty tree mapper. You seem to not like that.  For testing, it's just as good, no? Or did I miss something.

**Comment by tea-dragon** [comment]
It is very nearly as good, but tree mapper has tons of settings and log output. It would also be nice if it could be excluded as a potential problem while debugging an error.

**Comment by yuesong** [comment]
Fair enough. I'll close this one and submit another PR.

**Pull request closed without merging**
