### PR TITLE
Add backoff param to JSONFetcher and related ValueFilters

### PR DESCRIPTION
**Pull request by alstaplesmoore**

### CODE REVIEW

**Comment by mspiegel** [comment]
I did the wrong thing earlier. For this example you want the callable to go ahead and throw the IOException and not wrap it in an UncheckedIOException.

**Comment by alstaplesmoore** [comment]
I retry on UncheckedIOException. My adhoc tests show retries working correctly on an invalid URL.

**Comment by mspiegel** [comment]
@alstaplesmoore can you take a look at this change: https://github.com/addthis/hydra/commit/862887c17c0ee400c76168cc6ae0c1441bbd9871? My request is that we do not wrap IOExceptions inside of UncheckedIOExceptions when it's not necessary.

**Comment by alstaplesmoore** [comment]
^ Looks fine

**Pull request merged**
